### ISSUE TITLE
ideas Keyboard learning language

### ISSUE THREAD

**Issue by Pantyhose-X** [KaustubhPatange/Kling#11]
Hello KaustubhPatange
I have a good idea you can develop a "listen"keyboard tool, The mother tongue is not English. Need to learn English, the market is very large
Applied to language learning. Pronunciation correction
Always speak typed keys Speak phonetic letters Phonetic letters are spoken when long pressing on keyboard keys and navigating by character.

example
https://www.youtube.com/watch?v=YPBn6D6pf78&feature=youtu.be&t=213

https://user-images.githubusercontent.com/42504385/127757873-c3c076d3-ce73-40b1-8f57-423459fc0c2f.MP4

you can base on [nvda](https://github.com/nvaccess/nvda)

* Close Screen Reader close all other voice prompts.
* Independent use keyboard Reader
![image](https://user-images.githubusercontent.com/42504385/125297889-c4f7f880-e37b-11eb-9731-7e0a20a47545.png)

Android or iOS you can make into input method, you can base on [OpenBoard](https://github.com/dslul/openboard) or [Simple Keyboard](https://github.com/rkkr/simple-keyboard) , built-in mozilla text-to-speech or call [google text-to-speech TTS apk](https://play.google.com/store/apps/details?id=com.google.android.tts&hl=en_US&gl=US).

Open Source TTS 
[Mozilla's Text-to-Speech](https://github.com/mozilla/TTS)
[coqui-ai TTS](https://github.com/coqui-ai/TTS)

**Comment by KaustubhPatange** [comment]
Thank you for the idea but developing something which is already there makes no sense. 

Also, I'm sure all default system keyboard on Android has voice typing feature. Eg: for my Pixel 2 device, you can enable it from "Voice Input" settings from "Language & Keyboard" in the Settings app which produce the same output as shown in the video for Android device. For IOS I've no clue since I don't own any IOS device.

All in all, since this feature already exists on many platforms & I specifically have absolutely no interest in developing such a program it makes no sense to build it again!
